apiVersion: apps/v1
kind: Deployment
metadata:
  name: mind-app
  labels:
    app: mind-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mind-app
  template:
    metadata:
      labels:
        app: mind-app
    spec:
      containers:
      - name: mind-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
