apiVersion: v1
kind: Service
metadata:
  name: mind-app-service
  labels:
    app: mind-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: mind-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
